# Generated by Django 4.2.7 on 2023-11-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_settings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'настройка', 'verbose_name_plural': 'Настройки'},
        ),
    ]
